version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend