package com.task.seb.util;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import lombok.Getter;

import java.util.Set;

import static java.util.Collections.unmodifiableSet;
import static java.util.EnumSet.complementOf;
import static java.util.EnumSet.of;

@Getter
public enum Currency {
  FJD("Fiji dollar"),
  MXN("Mexican peso"),
  // LVL("Latvian lats"),
  SCR("Seychelles rupee"),
  CDF("Congolese Franc"),
  BBD("Barbados dollar"),
  HNL("Lempira"),
  UGX("Uganda shilling"),
  // MXV("Mexican unidad de inversion (UDI)"),
  ZAR("South African rand"),
  STN("Dobra"),
  BSD("Bahamian dollar"),
  // SDD("Sudanese dinar"),
  // ZRN("New zaire"),
  IQD("Iraqi dinar"),
  CUP("Cuban peso"),
  GMD("Dalasi"),
  TWD("Taiwan new dollar"),
  RSD("Serbian dinar"),
  MYR("Malaysian ringgit"),
  FKP("Falkland islands pound"),
  XOF("CFA franc"),
  UYU("Peso Uruguayo"),
  CVE("Cape Verde escudo"),
  OMR("Rial Omani"),
  KES("Kenyan shilling"),
  SEK("Swedish krona"),
  BTN("Ngultrum"),
  GNF("Guinean franc"),
  MZN("Mozambique metical"),
  SVC("El Salvador colon"),
  ARS("Argentine peso"),
  QAR("Qatari rial"),
  IRR("Iranian rial"),
  // NLG("Netherlands guilder"),
  // XPD("Palladium"),
  THB("Thai baht"),
  UZS("Uzbekistan sum"),
  // XPF("CFP franc"),
  BDT("Bangladeshi taka"),
  LYD("Libyan dinar"),
  KWD("Kuwaiti dinar"),
  // XPT("Platinum"),
  RUB("Russian ruble"),
  ISK("Iceland krona"),
  // BEF("Belgian franc"),
  MKD("Macedonian denar"),
  DZD("Algerian dinar"),
  PAB("Panamanian balboa"),
  SGD("Singapore dollar"),
  KGS("Kyrgyzstan som"),
  // XAF("CFA franc BEAC"),
  // XAG("Silver"),
  // ATS("Austrian schilling"),
  CHF("Swiss franc"),
  // ITL("Italian lire"),
  DJF("Djibouti franc"),
  TZS("Tanzanian shilling"),
  // ADP("Andorran peseta"),
  VND("Vietnamese dong"),
  // XAU("Gold"),
  AUD("Australian dollar"),
  KHR("Riel"),
  IDR("Indonesian rupiah"),
  // XBA("European composite unit (EURCO)"),
  KYD("Cayman islands dollar"),
  // XBC("European unit of account-9 (EUA-9)"),
  // XBB("European monetary unit (EMU-6)"),
  BWP("Pula"),
  SHP("St. Helena pound"),
  // CYP("Cyprus pound"),
  // XBD("European unit of account-17 (EUA-17)"),
  TJS("Tajikistan somoni"),
  // TJR("Tajik ruble"),
  AED("UAE dirham"),
  RWF("Rwandan franc"),
  DKK("Danish krone"),
  BGN("Bulgarian lev"),
  MMK("Kyat"),
  NOK("Norwegian krone"),
  SYP("Syrian pound"),
  ZWL("Zimbabwe dollar"),
  LKR("Sri Lanka rupee"),
  CZK("Czech koruna"),
  // IEP("Irish pound"),
  // GRD("Greek drachma"),
  // XCD("East Caribbean dollar"),
  HTG("Gourde"),
  BHD("Bahraini dinar"),
  // SIT("Slovenian tolar"),
  // PTE("Portuguese escudo"),
  KZT("Kazakhstan tenge"),
  SZL("Lilangeni"),
  YER("Yemeni rial"),
  AFN("Afghani"),
  AWG("Aruban florin"),
  NPR("Nepalese rupee"),
  MNT("Mongolian tugrik"),
  GBP("Pound sterling"),
  BYN("Belarusian ruble"),
  HUF("Hungarian forint"),
  BYR("Belarusian ruble"),
  BIF("Burundi franc"),
  // XDR("SDR I.M.F."),
  BZD("Belize dollar"),
  MOP("Pataca"),
  NAD("Namibia dollar"),
  // SKK("Slovak koruna"),
  PEN("Peruvian sol"),
  WST("Tala"),
  TMT("Turkmenistan Manat"),
  // FRF("French franc"),
  // CLF("Unidad de fomento"),
  GTQ("Quetzal"),
  CLP("Chilean peso"),
  TND("Tunisian dinar"),
  SLE("Leone"),
  // XFO("Gold-franc (special settlement currency)"),
  DOP("Dominican peso"),
  KMF("Comorian franc"),
  // XFU("Uic-franc (special settlement currency)"),
  GEL("Georgian lari"),
  MAD("Moroccan dirham"),
  TOP("Pa'anga"),
  AZN("Azerbaijan manat"),
  PGK("Kina"),
  UAH("Ukrainian hryvnia"),
  ERN("Nakfa"),
  // TPE("Timor escudo"),
  CNY("Chinese yuan renminbi"),
  MRU("Ouguiya"),
  BMD("Bermudian dollar"),
  PHP("Philippine peso"),
  // XXX("Transactions without currency"),
  PYG("Guarani"),
  JMD("Jamaican dollar"),
  // GWP("Guinea-Bissau peso"),
  // ESP("Spanish peseta"),
  COP("Colombian peso"),
  USD("US dollar"),
  // USN("US dollar (Next day)"),
  ETB("Ethiopian birr"),
  // VEB("Venezuelan bolivar"),
  // ECS("Ecuadoran sucre"),
  SOS("Somali Shilling"),
  VUV("Vatu"),
  LAK("Lao kip"),
  BND("Brunei dollar"),
  // ECV("Unidad de valor"),
  LRD("Liberian dollar"),
  ALL("Albanian lek"),
  // MTL("Maltese lira"),
  VES("Venezuelan Bolivar"),
  ZMW("Zambian Kwacha"),
  ILS("Israeli Shekel"),
  GHS("Ghana cedi"),
  GYD("Guyana dollar"),
  KPW("North Korean won"),
  BOB("Bolivian boliviano"),
  MDL("Moldovan leu"),
  AMD("Armenian dram"),
  // MDR("Moldovan ruble"),
  TRY("Turkish lira"),
  LBP("Lebanese pound"),
  JOD("Jordanian dinar"),
  HKD("Hong Kong dollar"),
  EUR("Euro"),
  LSL("Loti"),
  CAD("Canadian dollar"),
  BOV("Mvdol"),
  // EEK("Estonian kroon"),
  MUR("Mauritius rupee"),
  GIP("Gibraltar pound"),
  RON("Romanian leu"),
  NGN("Naira"),
  CRC("Costa Rican colon"),
  PKR("Pakistan rupee"),
  ANG("Netherlands Antillean guilder"),
  SRD("Surinamese dollar"),
  LTL("Lithuanian litas"),
  SAR("Saudi riyal"),
  TTD("Trinidad and Tobago dollar"),
  MVR("Rufiyaa"),
  INR("Indian rupee"),
  KRW("South Korean won"),
  JPY("Japanese yen"),
  AOA("Kwanza"),
  PLN("Polish zloty"),
  SBD("Solomon Islands dollar"),
  // LUF("Luxembourg franc"),
  MWK("Malawi kwacha"),
  MGA("Malagasy ariary"),
  // FIM("Finnish markka"),
  // DEM("Deutsche mark"),
  BAM("Convertible marks"),
  EGP("Egyptian pound"),
  SSP("South Sudanese pound"),
  NIO("Cordoba oro"),
  NZD("New Zealand dollar"),
  BRL("Brazilian real"),
  @JsonEnumDefaultValue UNKNOWN("");

  private final String fullName;
  public static final Set<Currency> ALL_CURRENCIES = unmodifiableSet(complementOf(of(UNKNOWN, EUR)));

  Currency(String fullName) {
    this.fullName = fullName;
  }
}
